---
title: "Admin and service"
subtitle: "Academic service, editorial work, organisation and teaching"
description: "Academic service, editorial roles, grants, event organisation and teaching by Daniela Castro-Camilo at the University of Glasgow."
canonical-url: "https://dcastrocamilo.github.io/admin.html"
---

## Professional service

- Associate Editor, **Environmetrics**.
- Associate Editor, **Journal of the Royal Statistical Society, Series C**.
- Meeting Secretary, Environmental Statistics Section, Royal Statistical Society (2022-25).
- Chair, International Environmetrics Society Outreach and Liaison Committee (2023-2025).
- Elected Member, International Statistical Institute.

<!-- ## Event organisation and networks -->

<!-- - Co-founder, **GLE²N: Glasgow--Edinburgh Extremes Network**, a network for applied, theoretical and methodological work in statistical risk analysis and extreme value theory. [Link here](https://glen-scotland.github.io/glen/) -->
<!-- - Organiser, **INLA: Past, Present, and Future** biannual workshops. [Link here](https://inla-workshop.github.io/INLA-PastPresentFuture/) -->
<!-- - Co-organiser, **EnvEcoStats**, environmental and ecological statistics conference.  [Link here](https://lancasterextremes.co.uk/)). -->
<!-- - Organiser/co-organiser of invited sessions on extremes, environmental statistics and statistical risk. -->


## University roles

- Business, Industry, and Government Board chair ([BIG board chair](https://www.gla.ac.uk/schools/mathematicsstatistics/bigboard/))
- Research lead for Statistics.
- Exam Officer for Statistics (2022-25).
- Member of School of Mathematics & Statistics EDI committee.
- Academic adviser of studies for MSc students.

## Teaching

Recent teaching has included:

- **STATS4047 / STATS5022: Principles of Probability and Statistics**
- **STATS5103: Introduction to Statistical Programming in R and Python**
